#include "pch.hh"
#include "sim_n.hh"
#include "thermofluidics_n.hh"
#include "ui_n.hh"
#include "util_n.hh"
#include "pid_controller_t.hh"
#include "colo_t.hh"
#include "expression_parser_t.hh"
#include "prop_t.hh"
#include "render_t.hh"
#include "plot_t.hh"
#include "observerable_t.hh"
#include "rotational_mass_t.hh"
#include "throttle_cable_t.hh"
#include "sparkplug_t.hh"
#include "starter_motor_t.hh"
#include "port_t.hh"
#include "filter_t.hh"
#include "gas_t.hh"
#include "flame_t.hh"
#include "audio_processor_t.hh"
#include "volume_t.hh"
#include "node_t.hh"
#include "sdl_t.hh"
#include "ensim_t.hh"

int main()
{
    ensim_t{}.run();
}
